config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  concern :commentable do
    resources :comments
  end

  concern :votable do
    patch 'vote_up', to: 'votes#update'
    patch 'vote_down', to: 'votes#update'
  end

  resources :questions, concerns: [:votable, :commentable], shallow: true do
    resources :answers, concerns: [:votable, :commentable]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions
    end
  end

  get 'search/index'

  root to: 'questions#index'

  get 'tags/:tag', to: 'questions#index', as: 'tag'
end

app/models/question.rb
class Question < ActiveRecord::Base
  acts_as_votable
  is_impressionable
  belongs_to :user
  validates :title, presence: true, length: { maximum: 140 }
  validates :body, :user_id, presence: true
  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachmentable, dependent: :destroy
  has_many :comments, as: :commentable
  has_many :taggings
  has_many :tags, through: :taggings, dependent: :destroy
  accepts_nested_attributes_for :attachments
  scope :desc, -> { order('created_at DESC') }

  def show_object
    self
  end

  def show_title
    self.title
  end

  def show_body
    self.body
  end

  # Virtual attributes for question_params, which
  # received from the form data

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).questions
  end

  def score
    self.get_likes.size - self.get_dislikes.size
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  def index
    @questions = Question.all
    respond_with @questions
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  impressionist actions: [:show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :index, :show]
  before_action :build_answer, only: :show
  before_action :build_question, only: :create

  respond_to :js, only: :destroy

  def index
    if params[:tag]
      respond_with (@questions = Question.tagged_with(params[:tag]).desc.page(params[:page]).per(15))
    else
      respond_with (@questions = Question.desc.page(params[:page]).per(15))
    end
  end

  def show
    respond_with @question
  end

  def new
    respond_with (@question = Question.new)
  end

  def edit
  end

  def create
    respond_with @question
  end

  def update
    if @question.update(question_params)
      @question
    else
      render :edit
    end
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def build_question
    @user = current_user
    @question = @user.questions.create(question_params)
  end

  def question_params
    params.require(:question).permit(:title, :body, :all_tags, attachments_attributes: [:file])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def tag_links(tags)
    tags.split(',').map{|tag| link_to tag.strip, tag_path(tag.strip), class: 'post-tag' }.join(' ')
  end
end

app/views/questions/_all_questions.html.slim
ul.list-unstyled
  - @questions.each do |question|
    li id="question-#{question.id}"
      .question-summary
        .container-fluid
          .col-sm-1
            .row
              .votes.text-center
                | <span class="vote-count-post"><strong>#{question.score}</strong></span><br />
                .viewcount #{'vote'.pluralize(question.score)}
            .row
              - if question.answers.count > 0
                .status.text-center.answered
                  | <strong>#{question.answers.count}</strong><br />#{'answer'.pluralize(question.answers.count)}
              - else
                .status.text-center
                  | <strong>#{question.answers.count}</strong><br />#{'answer'.pluralize(question.answers.count)}

            .row
              .views.text-center= pluralize(question.impressionist_count, 'view')
          .col-sm-11
            h4= link_to question.title, question_path(question)
            p= truncate(question.body, length: 180)
            .post-taglist= raw tag_links(question.all_tags)
        - if user_signed_in? && question.user_id.to_s == current_user.id.to_s
          .row
            .col-md-offset-10.col-md-2.col-sm-offset-10.col-sm-2text-center
              = link_to 'Delete', question_path(question), method: :delete, remote: true, class: 'delete-question', data: {question_id: question.id, confirm: 'Are you sure?'}
.col-md-12.text-center= paginate @questions

app/views/questions/_answers.html.slim
- @question.answers.each do |answer|
  - if answer.persisted?
    .answer id="answer-#{answer.id}"
      .answer-content.panel.panel-default
        .panel-body
          p= markdown(answer.content)
          ul
            - answer.attachments.each do |a|
              li= link_to a.file.identifier, a.file.url, style: 'word-break: break-word;'
          - if user_signed_in? && answer.user_id.to_s == current_user.id.to_s
            ul.list-inline
              li
                p= link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
              li
                p= link_to 'Delete', answer_path(answer), class: 'delete-answer', data: { answer_id: answer.id, confirm: 'Are you sure?' }, method: :delete, remote: true
              = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}"} do |f|
                .form-group
                  = f.label :content, 'Answer'
                  = f.text_area :content, class: 'form-control', rows: 3
                .form-group
                  = f.submit 'Save', class: 'btn btn-primary'
                  = button_tag 'Cancel', :type => 'button', id: 'cancel-button', class: 'btn btn-default'
      .comments.col-md-offset-2.panel.panel-default
        .panel-body
          = render 'comments/list', parent: answer

app/views/questions/_questions.html.slim
- if @question.persisted?
  h2= @question.title
  hr
  div.panel.panel-default
    div.panel-body
      .row
        .col-md-1
          .vote_controls
            span.vote_up
              -if user_signed_in?
                = link_to vote_up_icon, question_vote_up_path(@question), method: :patch, remote: true
              -else
                = vote_up_icon
              span.rating = @question.score
              span.vote_down
                -if user_signed_in?
                  = link_to vote_down_icon, question_vote_down_path(@question), method: :patch, remote: true
                -else
                  = vote_down_icon
        .col-md-11= markdown(@question.body)
      .post-taglist= raw tag_links(@question.all_tags)
      - if user_signed_in? && @question.user_id.to_s == current_user.id.to_s
        p= link_to 'Edit', '', class: 'edit-question-link', data: { question_id: @question.id }
        = form_for @question, remote: true, html: { id: "edit-question-#{@question.id}"} do |f|
          .form-group
            = f.label :title
            = f.text_field :title, class: 'form-control'
          .form-group
            = f.label :body, 'Edit your question'
            = f.text_area :body, class: 'form-control', rows: 5
          .form-group
            = f.label :tags
            = f.text_field :all_tags, placeholder: 'Tags separated by comma', class: 'form-control'
          .form-group
            = f.submit 'Save', class: 'btn btn-primary'
      ul
        - @question.attachments.each do |a|
          li= link_to a.file.identifier, a.file.url, style: 'word-break: break-word;'

app/views/questions/destroy.js.erb
$('#question-<%= @question.id %>').remove();

app/views/questions/index.html.slim
h3 All questions
hr
.questions-list
  = render 'all_questions'

= subscribe_to "/questions/all"

app/views/questions/new.html.slim
.row
= form_for @question do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
    = f.label :body
    = f.text_area :body, class: 'form-control'
    = f.label :tags
    = f.text_field :all_tags, placeholder: 'Tags separated by comma', class: 'form-control'
    p Attachments:
    p
      = f.fields_for :attachments, @question.attachments.build do |a|
        = a.label :file
        = a.file_field :file, multiple: true, name: 'question[attachments_attributes][][file]'
  = f.submit 'Create', class: 'btn btn-primary'

app/views/questions/show.html.slim
.question-body
  = render 'questions'
  .comments.col-md-offset-1.panel.panel-default
    .panel-body
      = render 'comments/list', parent: @question
hr
.answers
  = render 'answers'
hr
- if user_signed_in?
  = form_for [@question, @answer], remote: true do |f|
    .form-group
      = f.label :content, 'Your answer'
      .answer-errors
      = f.text_area :content, class: 'form-control'
      = f.fields_for :attachments, @answer.attachments.build do |a|
        = a.label :file
        = a.file_field :file, multiple: true, name: 'answer[attachments_attributes][][file]'
    = f.submit 'Create', class: 'btn btn-primary'

/Subscribing to question channel. URL can be anything
= subscribe_to "/questions/#{@question.id}/answers"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
<% @question.errors.full_messages.each do |message| %>
$('.question-errors').html('<%= j message %>');
<% end %>
<% else %>
$('.question-body').html('<%= j render 'questions/questions' %>');
<% end %>