config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  concern :commentable do
    resources :comments
  end

  concern :votable do
    patch 'vote_up', to: 'votes#update'
    patch 'vote_down', to: 'votes#update'
  end

  resources :questions, concerns: [:votable, :commentable], shallow: true do
    resources :answers, concerns: [:votable, :commentable]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions
    end
  end

  get 'search/index'

  root to: 'questions#index'

  get 'tags/:tag', to: 'questions#index', as: 'tag'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  default_scope -> { order(:created_at) }
  validates :body, presence: true

  def show_title
    if commentable.is_a?(Question)
      commentable.title
    else
      commentable.question.title
    end
  end

  def show_object
    if commentable.is_a?(Question)
      self.commentable
    else
      self.commentable.question
    end
  end

  def show_body
    body
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_parent, except: :destroy
  before_action :load_comment, only: :destroy

  respond_to :js

  def create
    respond_with(@comment = @parent.comments.create(comment_params))
  end

  def destroy
    respond_with(@comment.destroy)
  end

  private

  def load_comment
    @comment = Comment.find(params[:id])
  end

  def load_parent
    @parent = Question.find(params[:question_id]) if params[:question_id]
    @parent ||= Answer.find(params[:answer_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_list.html.slim
.row
  ul.list-unstyled
    /= render parent.comments
    - parent.comments.each do |comment|
      li id="comment-#{comment.id}"
        .col-md-10= markdown(comment.body)
        - if user_signed_in?
          .col-md-2= link_to 'Delete', comment_path(comment), method: :delete, data: {confirm: 'Are you sure?'}, remote: true
- if user_signed_in?
  .add-comment-area
    p
      = link_to 'add a comment', '', class: 'add-comment-link'
    =form_for [parent, parent.comments.build], remote: true do |f|
      .form-group
        = f.label :body, 'Comment'
        = f.text_area :body, class: 'form-control', rows: 2
      .form-group
        = f.submit 'Post comment', class: 'btn btn-primary'
- else
  = link_to 'add a comment', new_user_session_path

app/views/comments/create.js.erb
var parentSelector = '<%= @parent.is_a?(Question) ? '.question-body' : "#answer-#{@parent.id}" %>';
$(parentSelector + ' .comments').html('<div class="panel-body"><%= j render 'list', parent: @parent %></div>');

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').remove();