config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  concern :commentable do
    resources :comments
  end

  concern :votable do
    patch 'vote_up', to: 'votes#update'
    patch 'vote_down', to: 'votes#update'
  end

  resources :questions, concerns: [:votable, :commentable], shallow: true do
    resources :answers, concerns: [:votable, :commentable]
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions
    end
  end

  get 'search/index'

  root to: 'questions#index'

  get 'tags/:tag', to: 'questions#index', as: 'tag'
end

app/views/layouts/_search_form.html.slim
= form_tag search_index_path, method: :get, class: 'navbar-form navbar-right', role: 'search' do |f|
  .form-group
    = text_field_tag :search, '', placeholder: 'search', size: 20, class: 'form-control input-sm'
    | &nbsp;
    = select_tag(:type, options_for_select([['All', 'ThinkingSphinx'],['Question','Question'], ['Answer', 'Answer'], ['Comment', 'Comment']]), class: 'form-control input-sm')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qna</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<section class="container">
  <section class="col-md-12">
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to 'StackOverHorse', root_path, class: 'navbar-brand' %>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                  <li>
                    <%= link_to('Ask question', new_question_path)  %>
                  </li>
                  <li>
                    <%= link_to(current_user.email, edit_user_registration_path)  %>
                  </li>
                  <li>
                    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                  </li>
              <% else %>
                  <li>
                    <%= link_to('Ask question', new_question_path)  %>
                  </li>
                  <li>
                    <%= link_to('Login', new_user_session_path)  %>
                  </li>
                  <li>
                    <%= link_to('Sign up', new_user_registration_path)  %>
                  </li>
              <% end %>
              <li>
                <%= render 'layouts/search_form' %>
              </li>

            </ul>
          </div>
        </div>
      </nav>
    <% if notice %>
        <div class="alert alert-success">
          <p class="notice"><%= notice %></p>
        </div>
    <% end %>
    <% if alert %>
        <div class="alert alert-warning">
          <p class="alert"><%= alert %></p>
        </div>
    <% end %>


    </section>


    <section class="col-md-12">
      <div class="row">
        <div class="col-sm-10">
          <%= yield %>
        </div>
      </div>
    </section>
  <section class="col-md-12">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4 text-center">Content</div>
      <div class="col-md-4"></div>
    </div>
  </section>
</section>


</body>
</html>